---
pipeline:

  build:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t solr .
    when:
      event: [push, pull_request]

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+docker_solr
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/solr
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event: push

  tag_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+docker_solr
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/solr
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
